import { Team, Player, Referee, Match, TournamentState } from './types';

export const INITIAL_TEAMS: Team[] = [
  {
    id: 'team-1',
    name: 'نجوم المستقبل',
    logoColor: 'bg-emerald-500',
    logoIcon: '⭐',
    schoolClass: 'الصف العاشر - أ',
    city: 'الرياض',
    points: 7,
    played: 3,
    wins: 2,
    draws: 1,
    losses: 0,
    goalsFor: 8,
    goalsAgainst: 3,
    goalDifference: 5,
  },
  {
    id: 'team-2',
    name: 'نمور التحدي',
    logoColor: 'bg-red-500',
    logoIcon: '🐯',
    schoolClass: 'الصف الحادي عشر - ب',
    city: 'جدة',
    points: 6,
    played: 3,
    wins: 2,
    draws: 0,
    losses: 1,
    goalsFor: 6,
    goalsAgainst: 4,
    goalDifference: 2,
  },
  {
    id: 'team-3',
    name: 'صقور الأثير',
    logoColor: 'bg-sky-500',
    logoIcon: '🦅',
    schoolClass: 'الصف الثاني عشر - ج',
    city: 'الدمام',
    points: 4,
    played: 3,
    wins: 1,
    draws: 1,
    losses: 1,
    goalsFor: 5,
    goalsAgainst: 5,
    goalDifference: 0,
  },
  {
    id: 'team-4',
    name: 'اتحاد القادة',
    logoColor: 'bg-amber-500',
    logoIcon: '👑',
    schoolClass: 'الصف العاشر - ب',
    city: 'مكة',
    points: 0,
    played: 3,
    wins: 0,
    draws: 0,
    losses: 3,
    goalsFor: 2,
    goalsAgainst: 9,
    goalDifference: -7,
  },
];

export const INITIAL_PLAYERS: Player[] = [
  // Team 1
  { id: 'p-1-1', name: 'أحمد الحربي', teamId: 'team-1', teamName: 'نجوم المستقبل', number: 10, position: 'FW', goals: 4, yellowCards: 1, redCards: 0 },
  { id: 'p-1-2', name: 'خالد العتيبي', teamId: 'team-1', teamName: 'نجوم المستقبل', number: 7, position: 'MF', goals: 2, yellowCards: 0, redCards: 0 },
  { id: 'p-1-3', name: 'ياسر القحطاني', teamId: 'team-1', teamName: 'نجوم المستقبل', number: 4, position: 'DF', goals: 1, yellowCards: 2, redCards: 0 },
  { id: 'p-1-4', name: 'عبد الله السديري', teamId: 'team-1', teamName: 'نجوم المستقبل', number: 1, position: 'GK', goals: 0, yellowCards: 0, redCards: 0 },
  { id: 'p-1-5', name: 'محمد الشمراني', teamId: 'team-1', teamName: 'نجوم المستقبل', number: 9, position: 'FW', goals: 1, yellowCards: 0, redCards: 0 },

  // Team 2
  { id: 'p-2-1', name: 'عمر السومة', teamId: 'team-2', teamName: 'نمور التحدي', number: 9, position: 'FW', goals: 3, yellowCards: 0, redCards: 0 },
  { id: 'p-2-2', name: 'سلمان الفرج', teamId: 'team-2', teamName: 'نمور التحدي', number: 8, position: 'MF', goals: 1, yellowCards: 1, redCards: 0 },
  { id: 'p-2-3', name: 'حسن معاذ', teamId: 'team-2', teamName: 'نمور التحدي', number: 2, position: 'DF', goals: 0, yellowCards: 0, redCards: 1 },
  { id: 'p-2-4', name: 'وليد عبد الله', teamId: 'team-2', teamName: 'نمور التحدي', number: 22, position: 'GK', goals: 0, yellowCards: 1, redCards: 0 },
  { id: 'p-2-5', name: 'فهد المولد', teamId: 'team-2', teamName: 'نمور التحدي', number: 11, position: 'FW', goals: 2, yellowCards: 0, redCards: 0 },

  // Team 3
  { id: 'p-3-1', name: 'سالم الدوسري', teamId: 'team-3', teamName: 'صقور الأثير', number: 10, position: 'MF', goals: 2, yellowCards: 0, redCards: 0 },
  { id: 'p-3-2', name: 'يحيى الشهري', teamId: 'team-3', teamName: 'صقور الأثير', number: 18, position: 'MF', goals: 1, yellowCards: 0, redCards: 0 },
  { id: 'p-3-3', name: 'أسامة هوساوي', teamId: 'team-3', teamName: 'صقور الأثير', number: 3, position: 'DF', goals: 1, yellowCards: 1, redCards: 0 },
  { id: 'p-3-4', name: 'محمد العويس', teamId: 'team-3', teamName: 'صقور الأثير', number: 1, position: 'GK', goals: 0, yellowCards: 0, redCards: 0 },
  { id: 'p-3-5', name: 'هتان باهبري', teamId: 'team-3', teamName: 'صقور الأثير', number: 17, position: 'FW', goals: 1, yellowCards: 0, redCards: 0 },

  // Team 4
  { id: 'p-4-1', name: 'محمد السهلاوي', teamId: 'team-4', teamName: 'اتحاد القادة', number: 10, position: 'FW', goals: 1, yellowCards: 0, redCards: 0 },
  { id: 'p-4-2', name: 'تيسير الجاسم', teamId: 'team-4', teamName: 'اتحاد القادة', number: 17, position: 'MF', goals: 1, yellowCards: 2, redCards: 0 },
  { id: 'p-4-3', name: 'عمر هوساوي', teamId: 'team-4', teamName: 'اتحاد القادة', number: 4, position: 'DF', goals: 0, yellowCards: 1, redCards: 0 },
  { id: 'p-4-4', name: 'عبد الله المعيوف', teamId: 'team-4', teamName: 'اتحاد القادة', number: 1, position: 'GK', goals: 0, yellowCards: 0, redCards: 0 },
  { id: 'p-4-5', name: 'نوح الموسى', teamId: 'team-4', teamName: 'اتحاد القادة', number: 6, position: 'MF', goals: 0, yellowCards: 0, redCards: 0 },
];

export const INITIAL_REFEREES: Referee[] = [
  { id: 'ref-1', name: 'تركي الخضير', phone: '0501234567', type: 'main' },
  { id: 'ref-2', name: 'محمد الهويش', phone: '0502345678', type: 'main' },
  { id: 'ref-3', name: 'فهد المرداسي', phone: '0503456789', type: 'main' },
  { id: 'ref-4', name: 'شكري الحنفوش', phone: '0504567890', type: 'main' },
];

export const INITIAL_MATCHES: Match[] = [
  {
    id: 'match-1',
    homeTeamId: 'team-1',
    homeTeamName: 'نجوم المستقبل',
    awayTeamId: 'team-2',
    awayTeamName: 'نمور التحدي',
    refereeId: 'ref-1',
    refereeName: 'تركي الخضير',
    date: '2026-05-18',
    time: '17:00',
    scoreHome: 3,
    scoreAway: 1,
    status: 'finished',
    stage: 'الجولة 1',
    events: [
      { id: 'ev-1', type: 'goal', playerId: 'p-1-1', playerName: 'أحمد الحربي', teamId: 'team-1', minute: 15 },
      { id: 'ev-2', type: 'goal', playerId: 'p-2-1', playerName: 'عمر السومة', teamId: 'team-2', minute: 32 },
      { id: 'ev-3', type: 'goal', playerId: 'p-1-1', playerName: 'أحمد الحربي', teamId: 'team-1', minute: 54 },
      { id: 'ev-4', type: 'goal', playerId: 'p-1-2', playerName: 'خالد العتيبي', teamId: 'team-1', minute: 81 },
      { id: 'ev-5', type: 'yellow_card', playerId: 'p-1-3', playerName: 'ياسر القحطاني', teamId: 'team-1', minute: 45 },
    ],
  },
  {
    id: 'match-2',
    homeTeamId: 'team-3',
    homeTeamName: 'صقور الأثير',
    awayTeamId: 'team-4',
    awayTeamName: 'اتحاد القادة',
    refereeId: 'ref-2',
    refereeName: 'محمد الهويش',
    date: '2026-05-18',
    time: '19:30',
    scoreHome: 2,
    scoreAway: 1,
    status: 'finished',
    stage: 'الجولة 1',
    events: [
      { id: 'ev-6', type: 'goal', playerId: 'p-3-1', playerName: 'سالم الدوسري', teamId: 'team-3', minute: 22 },
      { id: 'ev-7', type: 'goal', playerId: 'p-4-2', playerName: 'تيسير الجاسم', teamId: 'team-4', minute: 40 },
      { id: 'ev-8', type: 'goal', playerId: 'p-3-3', playerName: 'أسامة هوساوي', teamId: 'team-3', minute: 73 },
    ],
  },
  {
    id: 'match-3',
    homeTeamId: 'team-1',
    homeTeamName: 'نجوم المستقبل',
    awayTeamId: 'team-3',
    awayTeamName: 'صقور الأثير',
    refereeId: 'ref-1',
    refereeName: 'تركي الخضير',
    date: '2026-05-19',
    time: '17:00',
    scoreHome: 2,
    scoreAway: 2,
    status: 'finished',
    stage: 'الجولة 2',
    events: [
      { id: 'ev-9', type: 'goal', playerId: 'p-1-1', playerName: 'أحمد الحربي', teamId: 'team-1', minute: 10 },
      { id: 'ev-10', type: 'goal', playerId: 'p-3-1', playerName: 'سالم الدوسري', teamId: 'team-3', minute: 45 },
      { id: 'ev-11', type: 'goal', playerId: 'p-1-5', playerName: 'محمد الشمراني', teamId: 'team-1', minute: 60 },
      { id: 'ev-12', type: 'goal', playerId: 'p-3-5', playerName: 'هتان باهبري', teamId: 'team-3', minute: 88 },
    ],
  },
  {
    id: 'match-4',
    homeTeamId: 'team-2',
    homeTeamName: 'نمور التحدي',
    awayTeamId: 'team-4',
    awayTeamName: 'اتحاد القادة',
    refereeId: 'ref-3',
    refereeName: 'فهد المرداسي',
    date: '2026-05-19',
    time: '19:30',
    scoreHome: 3,
    scoreAway: 0,
    status: 'finished',
    stage: 'الجولة 2',
    events: [
      { id: 'ev-13', type: 'goal', playerId: 'p-2-1', playerName: 'عمر السومة', teamId: 'team-2', minute: 12 },
      { id: 'ev-14', type: 'goal', playerId: 'p-2-5', playerName: 'فهد المولد', teamId: 'team-2', minute: 44 },
      { id: 'ev-15', type: 'goal', playerId: 'p-2-5', playerName: 'فهد المولد', teamId: 'team-2', minute: 68 },
    ],
  },
  {
    id: 'match-5',
    homeTeamId: 'team-4',
    homeTeamName: 'اتحاد القادة',
    awayTeamId: 'team-1',
    awayTeamName: 'نجوم المستقبل',
    refereeId: 'ref-1',
    refereeName: 'تركي الخضير',
    date: '2026-05-20',
    time: '17:00',
    scoreHome: 1,
    scoreAway: 3,
    status: 'finished',
    stage: 'الجولة 3',
    events: [
      { id: 'ev-16', type: 'goal', playerId: 'p-4-1', playerName: 'محمد السهلاوي', teamId: 'team-4', minute: 5 },
      { id: 'ev-17', type: 'goal', playerId: 'p-1-1', playerName: 'أحمد الحربي', teamId: 'team-1', minute: 23 },
      { id: 'ev-18', type: 'goal', playerId: 'p-1-2', playerName: 'خالد العتيبي', teamId: 'team-1', minute: 48 },
      { id: 'ev-19', type: 'goal', playerId: 'p-1-5', playerName: 'محمد الشمراني', teamId: 'team-1', minute: 75 },
    ],
  },
  {
    id: 'match-6',
    homeTeamId: 'team-2',
    homeTeamName: 'نمور التحدي',
    awayTeamId: 'team-3',
    awayTeamName: 'صقور الأثير',
    refereeId: 'ref-2',
    refereeName: 'محمد الهويش',
    date: '2026-05-20',
    time: '19:30',
    scoreHome: 2,
    scoreAway: 1,
    status: 'live',
    stage: 'الجولة 3',
    events: [
      { id: 'ev-20', type: 'goal', playerId: 'p-2-1', playerName: 'عمر السومة', teamId: 'team-2', minute: 14 },
      { id: 'ev-21', type: 'goal', playerId: 'p-3-2', playerName: 'يحيى الشهري', teamId: 'team-3', minute: 34 },
      { id: 'ev-22', type: 'goal', playerId: 'p-2-2', playerName: 'سلمان الفرج', teamId: 'team-2', minute: 58 },
    ],
  },
  {
    id: 'match-7',
    homeTeamId: 'team-1',
    homeTeamName: 'نجوم المستقبل',
    awayTeamId: 'team-4',
    awayTeamName: 'اتحاد القادة',
    refereeId: 'ref-1',
    refereeName: 'تركي الخضير',
    date: '2026-05-21',
    time: '15:00',
    scoreHome: 0,
    scoreAway: 0,
    status: 'not_started',
    stage: 'نصف النهائي',
    events: [],
  },
  {
    id: 'match-8',
    homeTeamId: 'team-2',
    homeTeamName: 'نمور التحدي',
    awayTeamId: 'team-3',
    awayTeamName: 'صقور الأثير',
    refereeId: 'ref-2',
    refereeName: 'محمد الهويش',
    date: '2026-05-21',
    time: '18:00',
    scoreHome: 0,
    scoreAway: 0,
    status: 'not_started',
    stage: 'نصف النهائي',
    events: [],
  }
];

export const INITIAL_TOURNAMENT_STATE: TournamentState = {
  type: 'league',
  teams: INITIAL_TEAMS,
  players: INITIAL_PLAYERS,
  referees: INITIAL_REFEREES,
  matches: INITIAL_MATCHES,
  isStarted: true,
};
